### ISSUE TITLE
Can't update user with no compary

### ISSUE THREAD

**Issue by davisn** [textmagic/textmagic-rest-python#12]
In `examples/test_users.py`, we grab the user via `self.client.user.get()`.  We then proceed to update the user:

```
        updated = self.client.user.update(
            firstName=user.firstName,
            lastName=user.lastName,
            company=user.company
        )
```

In my case, however, `user.company` is `None`, and the update fails with the following exception:

```
Traceback (most recent call last):
  File "test_users.py", line 219, in test_mono_example
    company=user.company
  File "/home/ndavis/devel/textmagic-rest-python/python/lib/python2.7/site-packages/textmagic-2.0.3-py2.7.egg/textmagic/rest/models/user.py", line 74, in update
    response, instance = self.request("PUT", self.uri, data=kwargs)
  File "/home/ndavis/devel/textmagic-rest-python/python/lib/python2.7/site-packages/textmagic-2.0.3-py2.7.egg/textmagic/rest/models/base.py", line 156, in request
    response = make_tm_request(method, uri, auth=self.auth, **kwargs)
  File "/home/ndavis/devel/textmagic-rest-python/python/lib/python2.7/site-packages/textmagic-2.0.3-py2.7.egg/textmagic/rest/models/base.py", line 121, in make_tm_request
    response = make_request(method, uri, **kwargs)
  File "/home/ndavis/devel/textmagic-rest-python/python/lib/python2.7/site-packages/textmagic-2.0.3-py2.7.egg/textmagic/rest/models/base.py", line 81, in make_request
    raise ValueError('data should be an integer, '
ValueError: data should be an integer, binary, or string, or sequence 
```

If I comment the `company=user.company` line above, the request is sent to the server, but fails to validate:

```
ERROR: test_mono_example (__main__.TestUsers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_users.py", line 218, in test_mono_example
    lastName=user.lastName#,
  File "/home/ndavis/devel/textmagic-rest-python/python/lib/python2.7/site-packages/textmagic-2.0.3-py2.7.egg/textmagic/rest/models/user.py", line 74, in update
    response, instance = self.request("PUT", self.uri, data=kwargs)
  File "/home/ndavis/devel/textmagic-rest-python/python/lib/python2.7/site-packages/textmagic-2.0.3-py2.7.egg/textmagic/rest/models/base.py", line 156, in request
    response = make_tm_request(method, uri, auth=self.auth, **kwargs)
  File "/home/ndavis/devel/textmagic-rest-python/python/lib/python2.7/site-packages/textmagic-2.0.3-py2.7.egg/textmagic/rest/models/base.py", line 133, in make_tm_request
    msg=message, errors=errors)
TextmagicRestException: 
HTTP Error 400
Your request was:

PUT https://rest.textmagic.com/api/v2/user

Validation Failed

{u'fields': {u'company': [u'Please enter a valid company name.']}}
```

**Comment by andreylarionov** [comment]
You need to fill the 'Company' field in Account Details > Billing Details in your TextMagic Account to be able to update Users details using API. This field refers to Billing Details field. We recommend not to leave it blank.
