### ISSUE TITLE
Model.uri property is broken

### ISSUE THREAD

**Issue by davisn** [textmagic/textmagic-rest-python#2]
When I try to access the `uri` property of a `Model`,
I get an exception saying the object has to `base_uri` attribute.

For example:

```
>>> chats = client.chats.list()[0]
>>> chats
[<textmagic.rest.models.chats.Chat object at 0x25ba450>]
>>> chats[0].uri
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "textmagic/rest/models/base.py", line 170, in uri
    return "%s/%s" % (self.base_uri, self.name)
AttributeError: 'Chat' object has no attribute 'base_uri'
>>> 
```

**Comment by davisn** [comment]
This is apparently because of how `load` is implemented:

```
    def load(self, entries):
        del self.base_uri
        del self.auth
        self.__dict__.update(entries)
```
