### ISSUE TITLE
Chats.by_phone should not have default for phone parameter

### ISSUE THREAD

**Issue by davisn** [textmagic/textmagic-rest-python#3]
The `Chats.by_phone` specified a default value for its `phone` argument.  However, using the default results in an exception due to an invalid request (the phone number is invalid).

Since it is a required parameter, and there is no easy way to determine a valid default value, the default value should be removed.

**Comment by davisn** [comment]
Here's an example of the exception:

```
>>> chats = client.chats.by_phone()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "textmagic/rest/models/chats.py", line 111, in by_phone
    return self.get_subresource_instances(uid=phone, instance=chat_messages, params=kwargs)
  File "textmagic/rest/models/base.py", line 204, in get_subresource_instances
    response, page = self.request("GET", uri, params=params)
  File "textmagic/rest/models/base.py", line 156, in request
    response = make_tm_request(method, uri, auth=self.auth, **kwargs)
  File "textmagic/rest/models/base.py", line 133, in make_tm_request
    msg=message, errors=errors)
textmagic.rest.exceptions.TextmagicRestException: 
HTTP Error 400
Your request was:

GET https://rest.textmagic.com/api/v2/chats/0?

Invalid phone number specified

>>> 
```
