### ISSUE TITLE
Sporadic "rate limit is exceeded" running examples/test_contacts.py script

### ISSUE THREAD

**Issue by davisn** [textmagic/textmagic-rest-python#9]
When running the `examples/test_contacts.py` script, I get "rate limit is exceeded" errors on a regular basis (though not all the time).  The exact API call it fails on seems to vary between runs.  Here's a representative example:

```
ERROR: test_mono_example (__main__.TestContacts)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_contacts.py", line 101, in test_mono_example
    contacts, pager = self.client.contacts.list()
  File "/home/ndavis/devel/textmagic-rest-python/python/lib/python2.7/site-packages/textmagic-2.0.3-py2.7.egg/textmagic/rest/models/contacts.py", line 63, in list
    return self.get_instances(kwargs)
  File "/home/ndavis/devel/textmagic-rest-python/python/lib/python2.7/site-packages/textmagic-2.0.3-py2.7.egg/textmagic/rest/models/base.py", line 194, in get_instances
    response, page = self.request("GET", uri, params=params)
  File "/home/ndavis/devel/textmagic-rest-python/python/lib/python2.7/site-packages/textmagic-2.0.3-py2.7.egg/textmagic/rest/models/base.py", line 156, in request
    response = make_tm_request(method, uri, auth=self.auth, **kwargs)
  File "/home/ndavis/devel/textmagic-rest-python/python/lib/python2.7/site-packages/textmagic-2.0.3-py2.7.egg/textmagic/rest/models/base.py", line 133, in make_tm_request
    msg=message, errors=errors)
TextmagicRestException: 
HTTP Error 429
Your request was:

GET https://rest.textmagic.com/api/v2/contacts?search=False
```

**Comment by davisn** [comment]
Actually, I seem to get this on other scripts as well.  It seems the limit is a little less than 2 requests per second?  Or perhaps it's a time synchronization issue (assuming there are multiple servers that might handle any given request)?

**Comment by andreylarionov** [comment]
Yes, there is probably some sort of a difference in fractions of a millisecond on the client and the server. I increased interval value.
